analyzer:
  errors:
    unused_import: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false  
