name: p2p_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>= 3.1.3 <4.0.0'

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_stripe: ^12.0.2
  http: ^1.5.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2

  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.11.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/icons.png 
    - images/logo.png
    - images/profile_avatar.png